data:
  dataset_roots:
    # - Datasets/Coco
    # - Datasets/mpii_human_pose_v1
    # - Datasets/leeds-sport-pose-main
    - Datasets/padel/padel_pose
  splits:
    train: person_keypoints_train.json
    val: person_keypoints_val.json
  use_gt_bbox: [False, True, True, False] # True or False for each dataset. put to False for padel_pose
  images_dir: images
  image_size: [192, 256]        # w, h
  num_keypoints: 18
  batch_size: 32
  num_workers: 16

model:
  model_file: models/collection/pose_modularnet.py
  name: ModularNet
  image_size: [192, 256] 
  heatmap_size: [48, 64]
  num_keypoints: 18
  backbone: resnet18.a1_in1k #convnext_large.fb_in1k  
  head: deconv_head
  is_backbone_pretrained: True # Use ImageNet pretrained weights from TIMM's library
  pretrained : '' # Exemple: outputs/pose/convnext_finetune_4/checkpoints/convnext_finetune_4.ckpt

train:
  max_epochs: 200
  lr: 0.001
  lr_step: 20
  lr_gamma: 0.5
  min_lr: 1e-6
  output_dir: outputs/
  evaluation_config: COCO_and_racket # Evaluation style: choose between COCO_and_racket, COCO, racket, useful_keypoints. see more in datasets/coco_evaluator.py 